---
- name: set php_executable variable to a default if not defined
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: check if composer is installed
  stat:
    path: "{{ php_composer_bin_path }}"
  register: composer_bin

- name: download composer installer
  when: not composer_bin.stat.exists
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: run composer installer
  when: not composer_bin.stat.exists
  command: "{{ php_executable }} composer-installer.php"
  args:
    chdir: /tmp

- name: move composer info globally-accessible location
  when: not composer_bin.stat.exists
  shell: mv /tmp/composer.phar {{ php_composer_bin_path }}
  args:
    creates: "{{ php_composer_bin_path }}"

- name: update composer to latest version
  shell: "{{ php_executable }} {{ php_composer_bin_path }} self-update"
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"

- name: ensure composer directory exists
  file:
    path: "{{ composer_home_path }}"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"
    state: directory

- name: add github oauth token for composer (if configured)
  when: composer_github_oauth_token != ''
  become: yes
  become_user: "{{ composer_home_owner }}"
  template:
    src: "auth.json.j2"
    dest: "{{ composer_home_path }}/auth.json"
    owner: "{{ composer_home_owner }}"
    group: "{{ composer_home_group }}"