---
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
  with_items:
    - "{{ pid_dir }}"
    - "{{ log_dir }}"
    - "{{ conf_dir }}"

- name: create data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
  with_items:
    - "{{ data_dirs }}"

- name: copy configuration file
  template:
    src: elasticsearch.yml.j2
    dest: "{{ conf_dir }}/elasticsearch.yml"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0644
    force: yes
  register: config_updated
  notify: restart elasticsearch

- name: copy default file for instance
  template:
    src: elasticsearch.j2
    dest: "{{ instance_default_file }}"
    mode: 0644
    force: yes
  notify: restart elasticsearch

- name: copy init file for instance
  template:
    src: init/elasticsearch.j2
    dest: "{{ instance_init_script }}"
    mode: 0755
    force: yes
  when: not use_system_d
  notify: restart elasticsearch

- name: copy systemd file for instance
  template:
    src: systemd/elasticsearch.j2
    dest: "{{ instance_sysd_script }}"
    mode: 0644
    force: yes
  when: use_system_d
  notify:
    - reload systemd configuration
    - restart elasticsearch

- name: copy log4j2.properties file for instance
  template:
    src: log4j2.properties.j2
    dest: "{{ conf_dir }}/log4j2.properties"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0644
    force: yes
  notify: restart elasticsearch

- name: copy jvm.options file for instance
  template:
    src: jvm.options.j2
    dest: "{{ conf_dir }}/jvm.options"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0644
    force: yes
  notify: restart elasticsearch

- name: Delete Default Init
  file: dest=/etc/init.d/elasticsearch state=absent

- name: Delete Default Environment File
  file: dest=/etc/sysconfig/elasticsearch state=absent

- name: Delete Default Sysconfig File
  file: dest="{{ sysd_script }}" state=absent

- name: Delete Default Configuration File
  file: dest=/etc/elasticsearch/elasticsearch.yml state=absent
  when: not es_conf_dir.startswith('/etc/elasticsearch')

- name: Delete Default Logging File
  file: dest=/etc/elasticsearch/logging.yml state=absent
  when: not es_conf_dir.startswith('/etc/elasticsearch')

- name: Delete Default Logging File
  file: dest=/etc/elasticsearch/log4j2.properties state=absent
  when: not es_conf_dir.startswith('/etc/elasticsearch')

- name: Delete Default JVM Options File
  file: dest=/etc/elasticsearch/jvm.options state=absent
  when: not es_conf_dir.startswith('/etc/elasticsearch')