---
- name: add elasticsearch repo
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch-{{ es_major_version }}.repo
  when: es_use_repository

- name: include versionlock
  include: _elasticsearch-version-lock.yml
  when: es_version_lock

- name: install elasticsearch
  yum:
    name: elasticsearch{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %}
    state: present
    update_cache: yes
  when: es_use_repository
  register: elasticsearch_install_from_repo
  until: '"failed" not in elasticsearch_install_from_repo'
  retries: 5
  delay: 10

- name: install elasticsearch from url
  yum:
    name: "{% if es_custom_package_url is defined %}{{ es_custom_package_url }}{% else %}{{ es_package_url }}-{{ es_version }}.noarch.rpm{% endif %}"
    state: present
  when: not es_use_repository
  register: elasticsearch_install_from_package