---
- name: generate init script
  when: ansible_service_mgr|default() != "systemd"
  template:
    src: init.d/haproxy.init.j2
    dest: /etc/init.d/haproxy
    mode: 0755

- name: generate haproxy systemd service
  when: ansible_service_mgr|default() == "systemd"
  template:
    src: systemd/haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
    mode: 0644
  register: haproxy_unit_file

- name: create systemd tmpfiles configuration
  when:
    - ansible_service_mgr|default() == 'systemd'
    - haproxy_chroot_dir.startswith('/var/run') or haproxy_chroot_dir.startswith('/run')
  template:
    src: etc/tmpfiles.d/haproxy.conf.j2
    dest: /etc/tmpfiles.d/haproxy.conf
    mode: 0644

- name: reload systemd daemon
  command: systemctl daemon-reload
  when:
    - ansible_service_mgr|default() == "systemd"
    - haproxy_unit_file|changed

- name: set haproxy to start at boot
  service:
    name: haproxy
    enabled: yes

- name: flush handlers to apply config changes
  meta: flush_handlers

- name: ensure haproxy is running
  service:
    name: haproxy
    state: started