---
- name: Check if EPEL repo is already configured
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo
  when: not epel_repofile_result.stat.exists
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  retries: 5
  delay: 10

- name: Import EPEL GPG key
  when: not epel_repofile_result.stat.exists
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
  ignore_errors: "{{ ansible_check_mode }}"